export default {
    "login": "masturdating1991",
    "id": 48363598,
    "node_id": "MDQ6VXNlcjQ4MzYzNTk4",
    "avatar_url": "https://avatars.githubusercontent.com/u/48363598?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/masturdating1991",
    "html_url": "https://github.com/masturdating1991",
    "followers_url": "https://api.github.com/users/masturdating1991/followers",
    "following_url": "https://api.github.com/users/masturdating1991/following{/other_user}",
    "gists_url": "https://api.github.com/users/masturdating1991/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/masturdating1991/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/masturdating1991/subscriptions",
    "organizations_url": "https://api.github.com/users/masturdating1991/orgs",
    "repos_url": "https://api.github.com/users/masturdating1991/repos",
    "events_url": "https://api.github.com/users/masturdating1991/events{/privacy}",
    "received_events_url": "https://api.github.com/users/masturdating1991/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Ali Ghodousi",
    "company": null,
    "blog": "",
    "location": "Tehran",
    "email": null,
    "hireable": null,
    "bio": "html, css, bootstrap, sass, javascript, jquery, react",
    "twitter_username": null,
    "public_repos": 45,
    "public_gists": 0,
    "followers": 27,
    "following": 18,
    "created_at": "2019-03-08T18:02:59Z",
    "updated_at": "2021-01-21T08:43:25Z"
};
